export const CATEGORY_ICONS = {
  "Animales": "🦁",
  "Profesiones": "👨‍⚕️",
  "Comida": "🍕",
  "Países": "🌎",
  "Lugares": "🏥",
  "Jugadores de Fútbol": "⚽",
  "Películas": "🎬",
  "Deportes": "🏀",
  "Marcas": "🏷️"
};

export const CATEGORIES_CLUSTERED = {
  "Animales": [
    ["León", "Tigre", "Pantera", "Leopardo", "Guepardo", "Puma", "Lince"],
    ["Elefante", "Hipopótamo", "Rinoceronte", "Jirafa"],
    ["Delfín", "Ballena", "Foca", "Morsa", "Pingüino", "Oso Polar"],
    ["Gato", "Perro", "Conejo", "Liebre"],
    ["Lobo", "Zorro", "Mapache", "Ardilla", "Ciervo", "Alce"],
    ["Águila", "Halcón", "Búho", "Lechuza", "Cuervo", "Loro", "Guacamayo", "Pavo Real", "Avestruz"],
    ["Serpiente", "Iguana", "Camaleón", "Tortuga", "Cocodrilo"],
    ["Caballo", "Vaca", "Cerdo"],
    ["Mono", "Gorila", "Chimpancé"],
    ["Canguro", "Koala", "Ornitorrinco"],
    ["Araña", "Escorpión", "Hormiga", "Abeja", "Mariposa"],
    ["Rana", "Sapo"],
    ["Oso"]
  ],
  "Profesiones": [
    ["Médico", "Enfermero", "Odontólogo", "Psicólogo", "Veterinario"],
    ["Abogado", "Juez", "Fiscal"],
    ["Ingeniero", "Arquitecto", "Diseñador", "Programador"],
    ["Policía", "Bombero", "Militar"],
    ["Actor", "Músico", "Cantante", "Bailarín"],
    ["Profesor", "Maestro", "Científico", "Biólogo", "Químico", "Físico"],
    ["Chef", "Panadero", "Carnicero"],
    ["Carpintero", "Plomero", "Electricista", "Mecánico", "Pintor"],
    ["Piloto", "Astronauta", "Conductor"],
    ["Periodista", "Fotógrafo", "Escritor"],
    ["Agricultor", "Ganadero", "Pescador"],
    ["Peluquero", "Maquillador", "Sastre"],
    ["Contador", "Político"]
  ],
  "Comida": [
    ["Pizza", "Lasagna", "Ravioles", "Ñoquis", "Canelones", "Pasta", "Risotto"],
    ["Hamburguesa", "Hot Dog", "Papas Fritas", "Pollo Frito"],
    ["Tacos", "Tacos al Pastor", "Burritos", "Quesadillas", "Enchiladas", "Nachos", "Guacamole"],
    ["Sushi", "Sashimi", "Ramen"],
    ["Asado", "Empanadas", "Milanesa", "Choripán", "Arepas"],
    ["Paella", "Ceviche", "Tortilla de papas", "Gazpacho"],
    ["Helado", "Gelatina", "Flan"],
    ["Croissant", "Macarons", "Churros", "Brownie", "Tarta de Manzana", "Cheesecake", "Tiramisú", "Galletas"],
    ["Panqueques", "Waffles", "Crepes"],
    ["Ensalada", "Sopa"],
    ["Hummus", "Falafel", "Shawarma", "Kebab"],
    ["Tofu", "Ratatouille"]
  ],
  "Países": [
    ["Argentina", "Uruguay", "Chile", "Paraguay", "Bolivia", "Perú", "Ecuador", "Colombia", "Venezuela", "Brasil"],
    ["México", "Estados Unidos", "Canadá"],
    ["España", "Portugal", "Italia", "Francia", "Alemania", "Bélgica", "Países Bajos", "Suiza", "Austria"],
    ["Reino Unido", "Irlanda", "Escocia"],
    ["Rusia", "Ucrania", "Bielorrusia", "Polonia"],
    ["Japón", "China", "Corea del Sur", "Corea del Norte", "Taiwán"],
    ["India", "Pakistán", "Bangladés", "Nepal"],
    ["Egipto", "Marruecos", "Argelia", "Túnez", "Libia"],
    ["Sudáfrica", "Nigeria", "Kenia", "Senegal", "Camerún"],
    ["Australia", "Nueva Zelanda", "Fiyi"],
    ["Arabia Saudita", "Emiratos Árabes Unidos", "Catar", "Irán", "Irak", "Siria"],
    ["Turquía", "Grecia"],
    ["Suecia", "Noruega", "Finlandia", "Dinamarca", "Islandia"],
    ["Cuba", "República Dominicana", "Puerto Rico", "Jamaica", "Haití", "Costa Rica", "Panamá", "Guatemala", "El Salvador", "Honduras"]
  ],
  "Lugares": [
    ["Playa", "Isla", "Oasis", "Puerto"],
    ["Montaña", "Volcán", "Cueva", "Mina"],
    ["Bosque", "Selva", "Pantano", "Campamento"],
    ["Río", "Lago", "Cascada", "Glaciar"],
    ["Hospital", "Clínica veterinaria", "Consultorio dental", "Farmacia"],
    ["Escuela", "Universidad", "Guardería", "Biblioteca"],
    ["Supermercado", "Centro Comercial", "Ferretería", "Panadería", "Carnicería", "Librería"],
    ["Gimnasio", "Estadio de Fútbol", "Cancha de tenis", "Pista de hielo", "Pista de bolos"],
    ["Restaurante", "Cafetería", "Pizzería", "Heladería"],
    ["Parque", "Parque nacional", "Parque de Diversiones", "Parque acuático", "Zoológico", "Acuario", "Circo"],
    ["Cine", "Teatro", "Ópera", "Estudio de televisión", "Estudio de grabación"],
    ["Museo", "Galería de arte", "Ruinas arqueológicas"],
    ["Aeropuerto", "Estación de Tren", "Estación de autobuses", "Estación de metro"],
    ["Banco", "Oficina", "Rascacielos", "Ayuntamiento", "Juzgado", "Embajada"],
    ["Estación de Policía", "Cárcel", "Base militar"],
    ["Estación de Bomberos", "Laboratorio", "Observatorio"],
    ["Iglesia", "Mezquita", "Sinagoga", "Templo", "Monasterio"],
    ["Peluquería", "Spa", "Discoteca", "Casino"],
    ["Hotel", "Motel", "Mansión", "Cabaña", "Asilo", "Orfanato"],
    ["Granja", "Rancho", "Viñedo", "Invernadero"],
    ["Cementerio"],
    ["Faro", "Crucero", "Barco pirata", "Submarino", "Estación espacial"]
  ],
  "Jugadores de Fútbol": [
    ["Lionel Messi", "Diego Maradona", "Mario Kempes", "Juan Román Riquelme", "Ángel Di María", "Sergio Agüero"],
    ["Cristiano Ronaldo", "Eusébio", "Luis Figo"],
    ["Pelé", "Ronaldinho", "Ronaldo Nazario", "Neymar Jr.", "Rivaldo", "Romario", "Cafú", "Roberto Carlos", "Kaká", "Vinícius Jr.", "Rodrygo"],
    ["Zinedine Zidane", "Kylian Mbappé", "Thierry Henry", "Michel Platini"],
    ["Andrés Iniesta", "Xavi Hernández", "Sergio Ramos", "Iker Casillas", "Carles Puyol", "Gerard Piqué", "Sergio Busquets"],
    ["Erling Haaland", "Robert Lewandowski", "Karim Benzema", "Luis Suárez", "Edinson Cavani"],
    ["Luka Modric", "Kevin De Bruyne", "Steven Gerrard", "Frank Lampard", "Paul Scholes", "Andrea Pirlo"],
    ["Dibu Martínez", "Julián Álvarez", "Enzo Fernández", "Rodrigo De Paul", "Cuti Romero", "Alexis Mac Allister", "Lautaro Martínez"],
    ["Gianluigi Buffon", "Manuel Neuer", "Alisson Becker", "Ederson", "Keylor Navas"],
    ["Paolo Maldini", "Franz Beckenbauer", "Daniel Passarella", "Thiago Silva", "Marquinhos", "Kalidou Koulibaly"]
  ],
  "Películas": [
    ["Titanic", "Avatar", "El Lobo de Wall Street", "Atrápame si puedes", "Náufrago", "Forrest Gump"],
    ["Avengers: Endgame", "Los Vengadores", "Iron Man", "Capitán América", "Thor", "Guardianes de la Galaxia", "Pantera Negra", "El Hombre Araña", "Spider-Man: Sin Camino a Casa"],
    ["X-Men", "Deadpool", "Wolverine", "Logan"],
    ["Star Wars: Una nueva esperanza", "El Imperio Contraataca", "El Retorno del Jedi"],
    ["El Padrino", "El Padrino 2", "Buenos Muchachos"],
    ["Matrix", "Matrix Recargado", "Inception (El Origen)", "Interstellar"],
    ["Jurassic Park", "Tiburón", "Alien", "Depredador", "Terminator 2"],
    ["El Señor de los Anillos: La Comunidad del Anillo", "Las Dos Torres", "El Retorno del Rey", "Harry Potter y la Piedra Filosofal", "Gladiador", "Corazón Valiente", "Troya", "300"],
    ["Toy Story", "Buscando a Nemo", "El Rey León", "Shrek", "Los Increíbles", "Monsters Inc.", "Up: Una aventura de altura", "Coco", "Intensamente", "Frozen", "Moana", "Mulán", "Aladdín", "La Bella y la Bestia", "La Sirenita", "Tarzán", "Hércules"],
    ["Batman: El Caballero de la Noche", "Joker", "Sexto Sentido", "El Resplandor", "Psicosis"],
    ["El Conjuro", "El Exorcista", "Halloween", "IT", "Pesadilla en la calle Elm", "Viernes 13", "Chucky", "Scream", "Saw"],
    ["Misión Imposible", "James Bond: Casino Royale", "Duro de Matar", "Rápido y Furioso", "Mad Max: Furia en el camino"],
    ["Pulp Fiction", "El Club de la Pelea", "Bastardos Sin Gloria", "Django Sin Cadenas", "Kill Bill", "Seven", "El Silencio de los Inocentes"],
    ["Mi Pobre Angelito", "Volver al Futuro", "Indiana Jones y los Cazadores del Arca Perdida", "E.T. el Extraterrestre", "Piratas del Caribe"]
  ],
  "Deportes": [
    ["Fútbol", "Fútbol Americano", "Rugby"],
    ["Básquet", "Vóley", "Handball (Balonmano)"],
    ["Tenis", "Ping Pong (Tenis de mesa)", "Bádminton"],
    ["Natación", "Waterpolo", "Remo", "Canotaje"],
    ["Boxeo", "Judo", "Taekwondo", "Karate", "Lucha Libre"],
    ["Ciclismo", "Atletismo", "Triatlón"],
    ["Béisbol", "Softbol", "Golf"],
    ["Gimnasia Artística", "Patinaje Artístico", "Esgrima", "Halterofilia (Levantamiento de pesas)", "Tiro con arco", "Tiro deportivo"],
    ["Surf", "Snowboard", "Esquí"],
    ["Automovilismo", "Motociclismo", "Skateboard"],
    ["Polo", "Equitación", "Hockey sobre césped", "Hockey sobre hielo"]
  ],
  "Marcas": [
    ["Nike", "Adidas", "Puma", "Reebok"],
    ["Apple", "Samsung", "Sony", "Microsoft", "Google"],
    ["Coca-Cola", "Pepsi", "Red Bull", "Heineken", "Corona"],
    ["McDonald's", "Burger King", "KFC", "Starbucks"],
    ["Toyota", "Ford", "Chevrolet", "BMW", "Mercedes-Benz", "Honda", "Tesla"],
    ["Amazon", "IKEA", "Zara", "H&M"],
    ["Disney", "Netflix", "Spotify", "Nintendo", "PlayStation", "Xbox"],
    ["Facebook", "Instagram", "TikTok", "WhatsApp"],
    ["Gucci", "Louis Vuitton", "Rolex"],
    ["L'Oréal", "Gillette", "Colgate", "Pampers"],
    ["Nestlé", "Danone", "Kellogg's"],
    ["Visa", "Mastercard", "PayPal"]
  ]
};
